name: CI/CD

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths-ignore: ["**/README.md"]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  avoid_reduncy:
#    runs-on: ubuntu-18.04
#    if: ${{ github.event_name == 'push' }}
#    steps:
#      - name: Cancel Previous Redundant Builds
#        uses: styfle/cancel-workflow-action@0.9.1
#        with:
#          access_token: ${{ github.token }}
  
  # build:
  #   runs-on: ubuntu-20.04


  deploy-storybook:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: build
        uses: actions/setup-node@v3
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm ci

      - run: npm run build:storybook

      - name: Deploy storybooks
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
